language: android
jdk: oraclejdk7
android:
  components:
    - extra-android-m2repository
    - extra-android-support
    - tools
    - build-tools-23.0.2
    - android-23
deploy:
  provider: releases
  api_key: $GIT_HUB_OAUTH
  file: ./build/outputs/apk/rototone-debug.apk
  skip_cleanup: true
  on:
    tags: true
